- name: install tools
  package:
    name: code
    state: present

- name: Install VS Code extensions
  become_user: "{{ actual_user }}"
  ansible.builtin.command: code --install-extension {{ item }}
  loop: "{{ vscode_extensions }}"
  register: vscode_ext_result
  changed_when: "'already installed' not in vscode_ext_result.stdout"