- name: Install required scanning packages
  apt:
    name:
      - sane-utils
      - libusb-0.1-4
    state: present

- name: Install Brother scanner driver
  apt:
    deb: "{{ role_path }}/files/brscan4-0.4.11-1.amd64.deb"

# now root can scan with naps2, but not my user...
- name: Ensure Brother scanner rules are present
  lineinfile:
    path: /etc/udev/rules.d/60-brother-brscan4-libsane-type1.rules
    line: "{{ item }}"
    create: yes
    mode: '0644'
  loop:
    - "# Brother scanners"
    - 'ATTRS{idVendor}=="04f9", MODE="0664", GROUP="scanner", ENV{libsane_matched}="yes"'
  register: udev_rules_changed
  
- name: Reload udev rules
  command: udevadm control --reload-rules
  when: udev_rules_changed.changed

- name: Trigger udev rules
  command: udevadm trigger
  when: udev_rules_changed.changed

#- name: Run Brother scanner setup
#  command: /usr/local/Brother/sane/setupSaneScan4 -i

#- name: Create symbolic links for scanner libraries
#  file:
#    src: "{{ item.src }}"
#    dest: "{{ item.dest }}"
#    state: link
#  loop:
#    - { src: "/usr/lib64/sane/libsane-brother4*", dest: "/usr/lib/x86_64-linux-gnu/sane/" }
#    - { src: "/usr/lib64/libbrcolm*", dest: "/usr/lib/x86_64-linux-gnu/" }

#- name: Ensure scanner group exists
#  group:
#    name: scanner
#    state: present

- name: Add user to scanner group
  user:
    name: "{{ actual_user }}"
    groups: scanner
    append: yes

# should not be necessary
#- name: Add user to saned group
#  user:
#    name: "{{ actual_user }}"
#    groups: saned
#    append: yes

- name: Download and install NAPS2
  apt:
    deb: https://github.com/cyanfish/naps2/releases/download/v7.5.3/naps2-7.5.3-linux-x64.deb
    state: present

- name: copy profiles.xml
  copy:
    src: naps2_profiles.xml
    dest: "/home/{{ actual_user }}/.config/naps2/profiles.xml"
    owner: "{{ actual_user }}"
    group: "{{ actual_user }}"