- name: Update package cache and upgrade all packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist
    force_apt_get: yes
  when: ansible_os_family == "Debian"

- name: Install Basic Tools
  package:
    name:
    - htop
    - curl
    - pwgen
    - tree
    - wget
    - tar
    - nano
    - ca-certificates
    - python3-psutil
    - thunderbird
    - gimp
    - keepassxc
    - geany
    - vlc
    - wireguard
    - openfortivpn
    - syncthing
    state: present

- name: Create Syncthing autostart entry
  become_user: "{{ actual_user }}"
  copy:
    content: |
      [Desktop Entry]
      Name=Start Syncthing
      GenericName=File synchronization
      Comment=Starts the main syncthing process in the background.
      Exec=/usr/bin/syncthing serve --no-browser --logfile=default
      Icon=syncthing
      Terminal=false
      Type=Application
      Keywords=synchronization;daemon;
      Categories=Network;FileTransfer;P2P
    dest: "/home/{{ actual_user }}/.config/autostart/syncthing-start.desktop"
    mode: '0644'

# Firewall für syncthing??

- name: Pause for 5 seconds to build app cache
  ansible.builtin.pause:
    seconds: 5

- name: Install TeamViewer
  apt:
    deb: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
    state: present

