- name: Update package cache and upgrade all packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist
    force_apt_get: yes
  when: ansible_os_family == "Debian"

- name: Install Basic Tools
  package:
    name:
    - htop
    - curl
    - pwgen
    - tree
    - wget
    - tar
    - nano
    - ca-certificates
    - python3-psutil
    - thunderbird
    - gimp
    - keepassxc
    - geany
    - vlc
    - wireguard
    - openfortivpn
    state: present

- name: Pause for 5 seconds to build app cache
  ansible.builtin.pause:
    seconds: 5

- name: Install TeamViewer
  apt:
    deb: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
    state: present

