- name: Create folder for marp slides
  become_user: "{{ actual_user }}"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /home/{{ actual_user }}/slides/

# hier die Marp Slides hinpacken???